apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-explorer-deployment
spec:
  selector:
    matchLabels:
      app: nginx-explorer
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-explorer
    spec:
      containers:
        - name: nginx80
          image: k8s033122acr.azurecr.io/nginx80-explorer:latest
          ports:
            - containerPort: 80
        - name: nginx81
          image: k8s033122acr.azurecr.io/nginx81-explorer:latest
          ports:
            - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-explorer-http
  labels:
    app: nginx-explorer
spec:
  type: LoadBalancer
  selector:
    app: nginx-explorer
  ports:
    - name: http80
      protocol: TCP
      port: 8080
      nodePort: 30080
      targetPort: 80
    - name: http81
      protocol: TCP
      port: 8081
      nodePort: 30081
      targetPort: 81
---
